name: Build Windows

on: [push]

jobs:
  build-d3d11:
    runs-on: windows-latest
    steps:
    - name: Install Haxe
      uses: krdlab/setup-haxe@master
      with:
          haxe-version: 4.1.3
    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
    - name: Checkout hashlink
      uses: actions/checkout@v2
      with:
        repository: "HaxeFoundation/hashlink"
        path: "hashlink"
    - name: Checkout KincHL
      uses: actions/checkout@v2
      with:
        path: "KincHL"
    - name: Checkout Kinc
      uses: actions/checkout@v2
      with:
        repository: "Kode/Kinc"
        path: "Kinc"
        submodules: "recursive"
    - name: Build Hashlink
      run: |
        cd hashlink
        haxe -cp ${env:GITHUB_WORKSPACE}/KincHL/extra/ --run Replacer libhl.vcxproj 8.1 10.0.19041.0
        MSBuild /nologo libhl.vcxproj -m -p:OutDir=bin\
    - name: Build KincHL
      run: |
        cd KincHL
        node ${env:GITHUB_WORKSPACE}/Kinc/make.js --dynlib --compile --noshaders
