name: Build Linux

on: [push]

jobs:
  build-opengl:
    runs-on: ubuntu-latest
    steps:
    - name: Install Haxe
      uses: krdlab/setup-haxe@master
      with:
          haxe-version: 4.1.3
    - name: Checkout hashlink
      uses: actions/checkout@v2
      with:
        repository: "HaxeFoundation/hashlink"
        path: "hashlink"
    - name: Checkout KincHL
      uses: actions/checkout@v2
      with:
        path: "KincHL"
    - name: Checkout Kinc
      uses: actions/checkout@v2
      with:
        repository: "Kode/Kinc"
        path: "Kinc"
        submodules: "recursive"
    - name: Apt Update
      run: sudo apt-get update
    - name: Apt Install
      run: sudo apt-get install libasound2-dev libxinerama-dev libxrandr-dev libgl1-mesa-dev libxi-dev libxcursor-dev --yes --quiet
    - name: Build Hashlink
      run: |
        cd hashlink
        make libhl
        cp libhl.so /usr/local/lib
    - name: Build KincHL
      run: |
        cd KincHL
        node ../Kinc/make.js --dynlib --compile --noshaders