name: Build MacOS

on: [push]

jobs:
  build-metal:
    runs-on: macos-latest
    steps:
    - name: Install Haxe
      uses: krdlab/setup-haxe@master
      with:
          haxe-version: 4.1.3
    - name: Checkout hashlink
      uses: actions/checkout@v2
      with:
        repository: "HaxeFoundation/hashlink"
        path: "hashlink"
    - name: Checkout KincHL
      uses: actions/checkout@v2
      with:
        path: "KincHL"
    - name: Checkout Kinc
      uses: actions/checkout@v2
      with:
        repository: "Kode/Kinc"
        path: "Kinc"
        submodules: "recursive"
    - name: Build Hashlink
      run: |
        cd hashlink
        make libhl
    - name: Build KincHL
      env:
        LD_LIBRARY_PATH: $GITHUB_WORKSPACE/hashlink:$LD_LIBRARY_PATH
      run: |
        cd KincHL
        node ../Kinc/make.js --dynlib --compile --noshaders