name: Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        graphics: [opengl]
        include:
          - os: macos-latest
            graphics: metal
          - os: windows-latest
            graphics: direct3d11
    steps:
    - name: Install Haxe
      uses: krdlab/setup-haxe@master
      with:
          haxe-version: 4.1.3
    - name: Checkout hashlink
      uses: actions/checkout@v2
      with:
        repository: "HaxeFoundation/hashlink"
        path: "hashlink"
    - name: Checkout KincHL
      uses: actions/checkout@v2
      with:
        path: "KincHL"
    - name: Checkout Kinc
      uses: actions/checkout@v2
      with:
        repository: "Kode/Kinc"
        path: "Kinc"
        submodules: "recursive"
    - name: Apt Update
      if: matrix.os == linux-latest
      run: sudo apt-get update
      continue-on-error: true
    - name: Apt Install
      if: matrix.os == linux-latest
      run: sudo apt-get install libasound2-dev libxinerama-dev libxrandr-dev libgl1-mesa-dev libxi-dev libxcursor-dev --yes --quiet
    - name: Build Hashlink
      if: matrix.os == linux-latest
      run: |
        cd hashlink
        make libhl
        sudo cp libhl.so /usr/local/lib
    - name: Build Hashlink
      if: matrix.os == macos-latest
      run: |
        cd hashlink
        make libhl
    - name: Build Hashlink
      if: matrix.os == windows-latest
      run: |
        cd hashlink
        haxe -cp ${env:GITHUB_WORKSPACE}/KincHL/extra/ --run Replacer libhl.vcxproj 8.1 10.0.19041.0
        MSBuild /nologo libhl.vcxproj -m -p:OutDir=bin\
    - name: Build KincHL
      run: |
        cd KincHL
        node ../Kinc/make.js --dynlib --compile --noshaders -g ${{matrix.graphics}}