name: Build Windows

on: [push, pull_request]

jobs:
  build-d3d11:
    runs-on: windows-latest
    env:
      HASHLINK_INCLUDE: $GITHUB_WORKSPACE/hashlink/src
      HASHLINK_BIN: $GITHUB_WORKSPACE/hashlink/bin
    steps:
    - name: Checkout hashlink
      uses: actions/checkout@v2
      with:
        repository: "HaxeFoundation/hashlink"
        path: "hashlink"
    - name: Checkout KincHL
      uses: actions/checkout@v2
      with:
        path: "KincHL"
    - name: Checkout Kinc
      uses: actions/checkout@v2
      with:
        repository: "Kode/Kinc"
        path: "Kinc"
        submodules: "recursive"
    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
    - name: Build Hashlink
      run: |
        cd hashlink
        MSBuild /nologo libhl.vcxproj -m -p:OutDir=bin\;ForceImportBeforeCppTargets="..\KincHL\extra\hl.props"
    - name: Install Haxe
      uses: krdlab/setup-haxe@master
      with:
          haxe-version: 4.1.3
    - name: Build KincHL
      run: |
        cd KincHL
        node ..\Kinc\make.js --dynlib --compile